export {default as LoginPage} from './LoginPage'
export {default as StudentPage} from './StudentPage'
export {default as SubjectsPage} from './SubjectsPage'
export {default as ProfilePage} from './ProfilePage'
export {default as RegisterPage} from './RegisterPage'
export {default as QuizPage} from './QuizPage'
export {default as TeacherHomePage} from './TeacherHomePage'